/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-01 06:19:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.badaro.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1633481257848L));
    _jspx_dependants.put("jar:file:/C:/Users/leehyungu/Desktop/my/badaro/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/badaro/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/leehyungu/Desktop/my/badaro/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/badaro/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board/boardList.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board/style_main.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board/post.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board/style_main.css\">\r\n");
      out.write("	    <!-- Custom fonts for this template -->\r\n");
      out.write("    <link href=\"/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- Custom styles for this page -->\r\n");
      out.write("    <link href=\"/resources/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/vendor/jquery/jquery.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("     <!-- modal창 start -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hiddn=\"true\">\r\n");
      out.write("    	<div class=\"modal-dialog\">\r\n");
      out.write("    		<div class=\"modal-content\">\r\n");
      out.write("    			<div class=\"modal-header\">\r\n");
      out.write("    				<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("    				<h4 class=\"modal-title\" id=\"myModalLabel\">Reply Modal</h4>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"modal-body\">\r\n");
      out.write("    				<div class=\"form-group\">\r\n");
      out.write("    					<label>Reply</label>\r\n");
      out.write("    					<input class=\"form-control\" name=\"reply\" value=\"New Reply!!!\">\r\n");
      out.write("    				</div>\r\n");
      out.write("    				<div class=\"form-group\">\r\n");
      out.write("    					<label>Replyer</label>\r\n");
      out.write("    					<input class=\"form-control\" name=\"replyer\" value=\"replyer\">\r\n");
      out.write("    				</div>\r\n");
      out.write("    				<div class=\"form-group\">\r\n");
      out.write("    					<label>Reply Date</label>\r\n");
      out.write("    					<input class=\"form-control\" name=\"replyDate\" value=\"\">\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div><!--  class=\"modal-body\" 끝 -->\r\n");
      out.write("    			<div class=\"modal-footer\">\r\n");
      out.write("    				<button id=\"modalModBtn\" type=\"button\" class=\"btn btn-warning\">Modify</button>\r\n");
      out.write("    				<button id=\"modalRemoveBtn\" type=\"button\" class=\"btn btn-danger\">Remove</button>\r\n");
      out.write("    				<button id=\"modalRegisterBtn\" type=\"button\" class=\"btn btn-primary\">Register</button>\r\n");
      out.write("    				<button id=\"modalCloseBtn\" type=\"button\" class=\"btn btn-default\">Close</button>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div><!--  class=\"modal-content\" 끝 -->\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <!-- modal창 end -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/resources/js/reply.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <header id=\"header\">\r\n");
      out.write("            <div class=\"headerIn\">\r\n");
      out.write("                <h1 class=\"logo\"><a href=\"/badaro/main/index\">바다로</a></h1>\r\n");
      out.write("                <div class=\"member\">\r\n");
      out.write("                    <p class=\"join\"><a href=\"\">마이페이지</a></p>\r\n");
      out.write("                    <p class=\"login\"><a href=\"\">로그아웃</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!--.headerIn-->\r\n");
      out.write("        </header><!--#header-->\r\n");
      out.write("        <div class=\"gnb\">\r\n");
      out.write("            <div class=\"aside\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"\">동해</a></li>\r\n");
      out.write("                    <li><a href=\"\">menu2</a></li>\r\n");
      out.write("                    <li><a href=\"\">menu3</a></li>\r\n");
      out.write("                    <li><a href=\"\">menu4</a></li>\r\n");
      out.write("                    <li><a href=\"\">menu5</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button><img src=\"img/btn_open.png\" alt=\"\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!--.gnb-->\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("            <div class=\"row1\"></div>\r\n");
      out.write("            <div class=\"text\">\r\n");
      out.write("                <div class=\"row2\">\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\" hidden>\r\n");
      out.write("						<label for=\"name\">작성자</label>\r\n");
      out.write("						<input class=\"form-control\" id=\"p_user\" name=\"p_user\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("						<label for=\"name\">조회수</label>\r\n");
      out.write("						<input class=\"form-control\" id=\"p_count\" name=\"p_count\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("						<input type=\"text\" id=\"p_turn\" name=\"p_turn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_turn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("	                <div class=\"r1btns\">\r\n");
      out.write("	                	<p class=\"change\"><a href=\"/badaro/board/modify?p_turn=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_turn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">수정</a></p>\r\n");
      out.write("	                    <p class=\"delete\"><a href=\"/badaro/board/remove?p_turn=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_turn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">삭제</a></p>\r\n");
      out.write("	               	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div> <!--.row2-->\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"row3\">\r\n");
      out.write("                    <div class=\"memo\">\r\n");
      out.write("                        <form action=\"\">\r\n");
      out.write("                            <p class=\"m1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${read.p_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> <!--.row3-->\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("	           	<div class=\"row\"><!-- class=\"row\" 시작 -->\r\n");
      out.write("					<div class=\"col-lg-12\"><!-- class=\"col-lg-12\" 시작 -->\r\n");
      out.write("						<div class=\"panel panel-default\"><!-- class=\"panel panel-default\" 시작 -->\r\n");
      out.write("							<div class=\"panel-heading\"><!-- class=\"panel-heading\" 시작 -->\r\n");
      out.write("								<i class=\"fa fa-comments fa-fw\"></i>Reply\r\n");
      out.write("								<button id=\"addReplyBtn\" class=\"btn btn-primary btn-xs pull-right\">댓글 쓰기</button>\r\n");
      out.write("							</div><!-- class=\"panel-heading\" 끝 -->\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"panel-body\"><!-- class=\"panel-body\" 시작 -->\r\n");
      out.write("								<ul class=\"chat\"><!-- class=\"chat\" 시작 -->\r\n");
      out.write("				\r\n");
      out.write("								</ul><!-- class=\"chat\" 끝-->\r\n");
      out.write("							</div><!-- class=\"panel-body\" 끝 -->\r\n");
      out.write("							<!-- .panel .chat-panel -->\r\n");
      out.write("							<div class=\"panel-footer\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div><!-- class=\"panel panel-default\" 끝 -->\r\n");
      out.write("					</div><!-- class=\"col-lg-12\" 끝 -->\r\n");
      out.write("				</div><!-- class=\"row\" 끝 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!--c-->\r\n");
      out.write("        \r\n");
      out.write("        <footer id=\"footer\">\r\n");
      out.write("            <div class=\"footerIn\">\r\n");
      out.write("                Footer\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer><!--#footer-->\r\n");
      out.write("    </div> <!--#wrap-->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/board/script_main.js\"></script>\r\n");
      out.write("        <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("            \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
